// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagement.Infrastructure;

#nullable disable

namespace TaskManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918095012_AddTaskConcurrencyVersion")]
    partial class AddTaskConcurrencyVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Tom Johnson",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            FullName = "David Tyson",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Mike Fischer",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("TaskManagement.Domain.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssigneeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PlannedStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatedByEmployeeId");

                    b.ToTable("Tasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tasks_CompletedAt_Consistent_With_Status", "(\"Status\" = 2 AND \"CompletedAt\" IS NOT NULL) OR (\"Status\" <> 2 AND \"CompletedAt\" IS NULL)");

                            t.HasCheckConstraint("CK_Tasks_Creator_Different_From_Assignee", "\"CreatedByEmployeeId\" <> \"AssigneeId\"");

                            t.HasCheckConstraint("CK_Tasks_DueAt_GreaterThanOrEqual_PlannedStartAt", "\"DueAt\" >= \"PlannedStartAt\"");

                            t.HasCheckConstraint("CK_Tasks_Status_Valid", "\"Status\" IN (0, 1, 2, 3)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssigneeId = 2,
                            CreatedByEmployeeId = 1,
                            Description = "Prepare the monthly sales report.",
                            DueAt = new DateTime(2026, 9, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            PlannedStartAt = new DateTime(2026, 9, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Title = "Prepare monthly report",
                            Version = 1L
                        },
                        new
                        {
                            Id = 2,
                            AssigneeId = 1,
                            CreatedByEmployeeId = 2,
                            Description = "Update internal project documentation.",
                            DueAt = new DateTime(2026, 9, 18, 18, 0, 0, 0, DateTimeKind.Utc),
                            PlannedStartAt = new DateTime(2026, 9, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Title = "Update documentation",
                            Version = 1L
                        },
                        new
                        {
                            Id = 3,
                            AssigneeId = 2,
                            CompletedAt = new DateTime(2026, 9, 4, 15, 30, 0, 0, DateTimeKind.Utc),
                            CreatedByEmployeeId = 1,
                            Description = "Prepare presentation for the team meeting.",
                            DueAt = new DateTime(2026, 9, 5, 18, 0, 0, 0, DateTimeKind.Utc),
                            PlannedStartAt = new DateTime(2026, 9, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            Title = "Prepare presentation",
                            Version = 1L
                        });
                });

            modelBuilder.Entity("TaskManagement.Domain.TaskItem", b =>
                {
                    b.HasOne("TaskManagement.Domain.Employee", "Assignee")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskManagement.Domain.Employee", "CreatedByEmployee")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("CreatedByEmployee");
                });

            modelBuilder.Entity("TaskManagement.Domain.Employee", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
